name: 3_on_job

on:
  push:
    branches:
      - 'feather'
      - 'master'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Build Signed APK
        uses: victorbnl/build-signed-apk@main
        with:
          keystore_b64: ${{ secrets.SIGNING_KEY }}
          keystore_password: ${{ secrets.KEY_STORE_PASSWORD }}
          key_alias: ${{ secrets.ALIAS }}
          key_password: ${{ secrets.KEY_PASSWORD }}


#      - name: Signing apk
#        id: Sign
#        uses: r0adkll/sign-android-release@v1
#        with:
#          releaseDirectory: app/build/outputs/apk/release
#          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
#          alias: ${{ secrets.ALIAS }}
#          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
#          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app/build/outputs/apk/release
